# frozen_string_literal: true

# Generate documentation/adr/traceability.md — the ADR <-> gem <-> invariant <-> test matrix
# GOAL.md promises ("traceability matrix in TAMOZ_AGENT_DESIGN.md") but never delivered.
# Derived, not hand-maintained: gems and invariant clauses come from each ADR's own text,
# tests from a scan of the test suites for ADR references. Stdlib only.
#
#   ruby script/adr_traceability.rb        # write traceability.md
#
# Wired as `rake adr:trace`.

ROOT = File.expand_path("..", __dir__)
ADR_DIR = File.join(ROOT, "documentation", "adr")
OUT = File.join(ADR_DIR, "traceability.md")

# index every test file once, so we can attribute each to the ADRs it references
test_files = Dir[File.join(ROOT, "test", "**", "*.rb")] +
             Dir[File.join(ROOT, "gems", "*", "test", "**", "*.rb")]
test_index = test_files.map { |p| [p.sub("#{ROOT}/", ""), File.read(p, encoding: Encoding::UTF_8)] }

rows = []
Dir[File.join(ADR_DIR, "adr-*.md")].sort.each do |path|
  text = File.read(path, encoding: Encoding::UTF_8)
  num = File.basename(path)[/^adr-(\d{3})-/, 1]
  title = text[/^\#\s+ADR-\d{3}\s+—\s+(.+?)(?:\s+\(RETIRED\))?$/, 1].to_s.strip
  tier = text[/^\*\*Tier:\*\*\s*([A-Z])/, 1] || "—"
  state = text =~ /^\*\*Status:\*\*\s*Retired/i ? "retired" : (text =~ /^\*\*Status:\*\*.*Proposed/ ? "proposed" : "accepted")

  gems = text.scan(/\btamoz-[a-z0-9]+(?:-[a-z0-9]+)*/).uniq.sort
  invs = text.scan(/(?:invariant|clause)\s+(\d+)/i).flatten.map(&:to_i).uniq.sort
  n = num.to_i
  test_re = /adr[-_ ]?0*#{n}\b/i
  tests = test_index.select { |(_, body)| body =~ test_re }.map(&:first).sort

  rows << { num: num, title: title, tier: tier, state: state, gems: gems, invs: invs, tests: tests }
end

def cell(list, empty = "—")
  list.empty? ? empty : list.map { |x| "`#{x}`" }.join(", ")
end

lines = []
lines << "# ADR traceability matrix"
lines << ""
lines << "Generated by `script/adr_traceability.rb` (`rake adr:trace`). For each decision:"
lines << "which **gems** it names (usually its implementers — occasionally a dependency or a"
lines << "deferred package), which **invariant** clauses it cites, and which **tests** reference"
lines << "it. This is the matrix"
lines << "[`GOAL.md`](../../docs/design-v0.1/GOAL.md) calls for — derived from the files, so it"
lines << "cannot drift. Blank cells are honest gaps, not errors: not every decision names a"
lines << "clause or has a dedicated test yet."
lines << ""
lines << "| ADR | Title | Tier | Gems (named) | Invariants | Tests |"
lines << "|---|---|---|---|---|---|"
rows.each do |r|
  next if r[:state] == "retired"
  link = "[#{r[:num]}](./#{File.basename(Dir[File.join(ADR_DIR, "adr-#{r[:num]}-*.md")].first)})"
  invs = r[:invs].empty? ? "—" : r[:invs].join(", ")
  tests = r[:tests].empty? ? "—" : r[:tests].map { |t| "`#{File.basename(t)}`" }.join("<br>")
  lines << "| #{link} | #{r[:title]} | #{r[:tier]} | #{cell(r[:gems])} | #{invs} | #{tests} |"
end
lines << ""
covered = rows.count { |r| r[:state] != "retired" && !r[:tests].empty? }
inforce = rows.count { |r| r[:state] != "retired" }
lines << "## Coverage snapshot"
lines << ""
lines << "- In-force ADRs: **#{inforce}**"
lines << "- With at least one referencing test: **#{covered}**"
lines << "- With a named invariant clause: **#{rows.count { |r| r[:state] != 'retired' && !r[:invs].empty? }}**"
lines << ""
lines << "## Next reads"
lines << ""
lines << "- [`README.md`](./README.md) — the ADR catalog"
lines << "- [`../architecture/invariants.md`](../architecture/invariants.md) — the invariant contract"

File.write(OUT, lines.join("\n") + "\n")
puts "wrote #{OUT} (#{inforce} in-force ADRs, #{covered} with tests)"
